
package FormQuanLyVatTu;

import formTest.formdangnhaptest;


public class MenuPart2 extends javax.swing.JFrame {

    
    public MenuPart2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        lbl_Vattu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Kho = new javax.swing.JLabel();
        lbl_nhacungcap = new javax.swing.JLabel();
        lbl_phieuxuat = new javax.swing.JLabel();
        lbl_phieunhap = new javax.swing.JLabel();
        lbl_phieuxuatCT = new javax.swing.JLabel();
        lbl_phieunhapCT = new javax.swing.JLabel();
        lbl_Coso = new javax.swing.JLabel();
        lbl_Thongbaottin = new javax.swing.JLabel();
        lbl_dangxuat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnVattu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        pnKho = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnNhaCP = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnPhieuxuat = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnPhieunhap = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnPhieuxuatCT = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnPhieunhapCT = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnCoso = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnThongtin = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnMenu.setBackground(new java.awt.Color(153, 153, 153));

        lbl_Vattu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Vattu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Vattu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconVattu.png"))); // NOI18N
        lbl_Vattu.setText("Vật Tư");
        lbl_Vattu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VattuMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconLogin.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USER");

        lbl_Kho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Kho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconKho.png"))); // NOI18N
        lbl_Kho.setText("Kho");
        lbl_Kho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhoMouseClicked(evt);
            }
        });

        lbl_nhacungcap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nhacungcap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nhacungcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNhacungcap.png"))); // NOI18N
        lbl_nhacungcap.setText("Nhà Cung Cấp");
        lbl_nhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nhacungcapMouseClicked(evt);
            }
        });

        lbl_phieuxuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phieuxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phieuxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconxuat.png"))); // NOI18N
        lbl_phieuxuat.setText("Phiếu Xuất");
        lbl_phieuxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_phieuxuatMouseClicked(evt);
            }
        });

        lbl_phieunhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phieunhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phieunhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNhap.png"))); // NOI18N
        lbl_phieunhap.setText("Phiếu Nhập");
        lbl_phieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_phieunhapMouseClicked(evt);
            }
        });

        lbl_phieuxuatCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phieuxuatCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phieuxuatCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconxuat.png"))); // NOI18N
        lbl_phieuxuatCT.setText("Phiếu Xuất CT");
        lbl_phieuxuatCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_phieuxuatCTMouseClicked(evt);
            }
        });

        lbl_phieunhapCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phieunhapCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_phieunhapCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNhap.png"))); // NOI18N
        lbl_phieunhapCT.setText("Phiếu Nhập CT");
        lbl_phieunhapCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_phieunhapCTMouseClicked(evt);
            }
        });

        lbl_Coso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Coso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Coso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconCOso.png"))); // NOI18N
        lbl_Coso.setText("Cơ Sở");
        lbl_Coso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CosoMouseClicked(evt);
            }
        });

        lbl_Thongbaottin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Thongbaottin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Thongbaottin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNotification.png"))); // NOI18N
        lbl_Thongbaottin.setText("Thông Báo T.Tin");
        lbl_Thongbaottin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThongbaottinMouseClicked(evt);
            }
        });

        lbl_dangxuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconOut.png"))); // NOI18N
        lbl_dangxuat.setText("Đăng Xuất");
        lbl_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_dangxuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Vattu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Kho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_nhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_phieuxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_phieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_phieuxuatCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_phieunhapCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Coso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Thongbaottin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_Vattu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_phieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_phieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_phieuxuatCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_phieunhapCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Coso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Thongbaottin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        pnVattu.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_add.png"))); // NOI18N
        jButton1.setText("Thêm");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_fix.png"))); // NOI18N
        jButton2.setText("Sửa");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_delete.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Đơn Giá:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Đơn Vị Tính:");

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tên Vật Tư:");

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Mã Vật Tư:");

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tìm Kiếm:");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vật Tư");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_restart.png"))); // NOI18N

        javax.swing.GroupLayout pnVattuLayout = new javax.swing.GroupLayout(pnVattu);
        pnVattu.setLayout(pnVattuLayout);
        pnVattuLayout.setHorizontalGroup(
            pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVattuLayout.createSequentialGroup()
                .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnVattuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnVattuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)))
                    .addGroup(pnVattuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVattuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnVattuLayout.setVerticalGroup(
            pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVattuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVattuLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnVattuLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnVattuLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(169, Short.MAX_VALUE))
                    .addGroup(pnVattuLayout.createSequentialGroup()
                        .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnVattuLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(pnVattuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(pnVattuLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addGap(114, 114, 114))))
        );

        jPanel3.add(pnVattu, "card10");

        jLabel9.setText("kho");

        javax.swing.GroupLayout pnKhoLayout = new javax.swing.GroupLayout(pnKho);
        pnKho.setLayout(pnKhoLayout);
        pnKhoLayout.setHorizontalGroup(
            pnKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhoLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(579, Short.MAX_VALUE))
        );
        pnKhoLayout.setVerticalGroup(
            pnKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhoLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel9)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jPanel3.add(pnKho, "card3");

        jLabel10.setText("nhaCP");

        javax.swing.GroupLayout pnNhaCPLayout = new javax.swing.GroupLayout(pnNhaCP);
        pnNhaCP.setLayout(pnNhaCPLayout);
        pnNhaCPLayout.setHorizontalGroup(
            pnNhaCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhaCPLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        pnNhaCPLayout.setVerticalGroup(
            pnNhaCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhaCPLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel10)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jPanel3.add(pnNhaCP, "card4");

        jLabel11.setText("phieuxuat");

        javax.swing.GroupLayout pnPhieuxuatLayout = new javax.swing.GroupLayout(pnPhieuxuat);
        pnPhieuxuat.setLayout(pnPhieuxuatLayout);
        pnPhieuxuatLayout.setHorizontalGroup(
            pnPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuxuatLayout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        pnPhieuxuatLayout.setVerticalGroup(
            pnPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuxuatLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel11)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jPanel3.add(pnPhieuxuat, "card5");

        jLabel13.setText("phieunhap");

        javax.swing.GroupLayout pnPhieunhapLayout = new javax.swing.GroupLayout(pnPhieunhap);
        pnPhieunhap.setLayout(pnPhieunhapLayout);
        pnPhieunhapLayout.setHorizontalGroup(
            pnPhieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieunhapLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel13)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        pnPhieunhapLayout.setVerticalGroup(
            pnPhieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieunhapLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel13)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        jPanel3.add(pnPhieunhap, "card6");

        jLabel14.setText("xuatCT");

        javax.swing.GroupLayout pnPhieuxuatCTLayout = new javax.swing.GroupLayout(pnPhieuxuatCT);
        pnPhieuxuatCT.setLayout(pnPhieuxuatCTLayout);
        pnPhieuxuatCTLayout.setHorizontalGroup(
            pnPhieuxuatCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuxuatCTLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        pnPhieuxuatCTLayout.setVerticalGroup(
            pnPhieuxuatCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuxuatCTLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel14)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        jPanel3.add(pnPhieuxuatCT, "card7");

        jLabel15.setText("nhapCT");

        javax.swing.GroupLayout pnPhieunhapCTLayout = new javax.swing.GroupLayout(pnPhieunhapCT);
        pnPhieunhapCT.setLayout(pnPhieunhapCTLayout);
        pnPhieunhapCTLayout.setHorizontalGroup(
            pnPhieunhapCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieunhapCTLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        pnPhieunhapCTLayout.setVerticalGroup(
            pnPhieunhapCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieunhapCTLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel15)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jPanel3.add(pnPhieunhapCT, "card8");

        jLabel16.setText("coso");

        javax.swing.GroupLayout pnCosoLayout = new javax.swing.GroupLayout(pnCoso);
        pnCoso.setLayout(pnCosoLayout);
        pnCosoLayout.setHorizontalGroup(
            pnCosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCosoLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        pnCosoLayout.setVerticalGroup(
            pnCosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCosoLayout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(267, 267, 267))
        );

        jPanel3.add(pnCoso, "card9");

        jLabel17.setText("thongtin");

        javax.swing.GroupLayout pnThongtinLayout = new javax.swing.GroupLayout(pnThongtin);
        pnThongtin.setLayout(pnThongtinLayout);
        pnThongtinLayout.setHorizontalGroup(
            pnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongtinLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        pnThongtinLayout.setVerticalGroup(
            pnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongtinLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel17)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jPanel3.add(pnThongtin, "card10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dangxuatMouseClicked
        formdangnhaptest dnt = new formdangnhaptest();
        dnt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_dangxuatMouseClicked

    private void lbl_VattuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VattuMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(true);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_VattuMouseClicked

    private void lbl_KhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(true);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_KhoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lbl_nhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nhacungcapMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(true);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_nhacungcapMouseClicked

    private void lbl_phieuxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_phieuxuatMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(true);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_phieuxuatMouseClicked

    private void lbl_phieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_phieunhapMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(true);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_phieunhapMouseClicked

    private void lbl_phieuxuatCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_phieuxuatCTMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(true);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_phieuxuatCTMouseClicked

    private void lbl_phieunhapCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_phieunhapCTMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(true);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_phieunhapCTMouseClicked

    private void lbl_CosoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CosoMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(true);
        pnThongtin.setVisible(false);
    }//GEN-LAST:event_lbl_CosoMouseClicked

    private void lbl_ThongbaottinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongbaottinMouseClicked
        // TODO add your handling code here:
        pnVattu.setVisible(false);
        pnKho.setVisible(false);
        pnNhaCP.setVisible(false);
        pnPhieunhap.setVisible(false);
        pnPhieuxuat.setVisible(false);
        pnPhieunhapCT.setVisible(false);
        pnPhieuxuatCT.setVisible(false);
        pnCoso.setVisible(false);
        pnThongtin.setVisible(true);
    }//GEN-LAST:event_lbl_ThongbaottinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPart2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPart2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPart2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPart2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPart2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbl_Coso;
    private javax.swing.JLabel lbl_Kho;
    private javax.swing.JLabel lbl_Thongbaottin;
    private javax.swing.JLabel lbl_Vattu;
    private javax.swing.JLabel lbl_dangxuat;
    private javax.swing.JLabel lbl_nhacungcap;
    private javax.swing.JLabel lbl_phieunhap;
    private javax.swing.JLabel lbl_phieunhapCT;
    private javax.swing.JLabel lbl_phieuxuat;
    private javax.swing.JLabel lbl_phieuxuatCT;
    private javax.swing.JPanel pnCoso;
    private javax.swing.JPanel pnKho;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnNhaCP;
    private javax.swing.JPanel pnPhieunhap;
    private javax.swing.JPanel pnPhieunhapCT;
    private javax.swing.JPanel pnPhieuxuat;
    private javax.swing.JPanel pnPhieuxuatCT;
    private javax.swing.JPanel pnThongtin;
    private javax.swing.JPanel pnVattu;
    // End of variables declaration//GEN-END:variables
}
